"$schema" = 'https://starship.rs/config-schema.json'

right_format = """$kubernetes"""

add_newline = false

[battery]
disabled = true

[character]
success_symbol = "[ï”](green)"
error_symbol = "[ï‘§](red)"

[package]
symbol = "ðŸ“¦ "
format = "[$symbol$version]($style) "


[directory]
truncate_to_repo = false

[username]
show_always = true
format = "[$user]($style) "

[git_branch]
symbol = "ï˜ "
style = 'green'
format = "[$symbol$branch(->$remote_branch)]($style) "

[git_commit]
tag_disabled = false

[python]
symbol = "î˜† "
format = '[${symbol}${pyenv_prefix}(${version}) (\($virtualenv\) )]($style)'

[kubernetes]
disabled = false
style = 'blue bold'
symbol = "ïˆš "
format = '[$symbol$context( \($namespace\))]($style)'
